TARGET_NAMES += deque
TARGET_NAMES += list
TARGET_NAMES += unordered_map
TARGET_NAMES += unordered_set
TARGET_NAMES += vector

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
