TARGET_NAMES += a\:\:static_test
TARGET_NAMES += c\:\:static_test
TARGET_NAMES += Curry
TARGET_NAMES += f\:\:static_test
TARGET_NAMES += IdentityWrapper
TARGET_NAMES += s\:\:static_test
TARGET_NAMES += t\:\:static_test

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
