TARGET_NAMES += get_plurality
TARGET_NAMES += normalize
TARGET_NAMES += unset_mask
TARGET_NAMES += upper_uniquify

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
