#pragma once
#ifndef UITSL_UTILITY_UITSL_STRINGIFY_HPP_INCLUDE
#define UITSL_UTILITY_UITSL_STRINGIFY_HPP_INCLUDE

#define UITSL_STRINGIFY(x) #x

#endif // #ifndef UITSL_UTILITY_UITSL_STRINGIFY_HPP_INCLUDE
