#pragma once
#ifndef UITSL_META_UITSL_NAMESPACE_HPP_INCLUDE
#define UITSL_META_UITSL_NAMESPACE_HPP_INCLUDE

#ifndef UITSL_NAMESPACE
#define UITSL_NAMESPACE() uitsl
#endif // #ifndef UITSL_NAMESPACE






#endif // #ifndef UITSL_META_UITSL_NAMESPACE_HPP_INCLUDE
