#!/bin/bash

trap "rm -f *.ranklog master.log" EXIT

function separate {
  printf '%50s\n' | tr ' ' -
}

function title {
  separate
  echo $1
  separate
}

MPIEXEC=${MPIEXEC:-mpiexec}


if [[ -t 1 ]]
then
  # show output interactively if running in terminal
  (echo $$; true | $MPIEXEC "$@"; echo done) > master.log &
  multitail -q 1 '*.ranklog'
  kill %1

  title "master.log"
  cat "master.log"
else
  # if non-interactive wait for job to finish then cat output
  title "master.log"
  $MPIEXEC "$@"
fi

for f in *.ranklog; do title $f; cat $f; done
