TARGET_NAMES += t\:\:BufferedIsendDuct
TARGET_NAMES += t\:\:IsendDuct

TO_ROOT := $(shell git rev-parse --show-cdup)

FLAGS = -std=c++17 -g -pthread -march=native -Wall -Wno-unused-function -Wno-include $(TO_ROOT)/tests/MaketemplateMultiproc
