#ifdef UIT_VENDORIZE_EMP

#ifdef EMP_ALWAYS_ASSERT_HPP
#define UIT_EMP_ALWAYS_ASSERT_HPP_HEADERGUARD
#endif // #ifdef EMP_ALWAYS_ASSERT_HPP
#pragma pop_macro("EMP_ALWAYS_ASSERT_HPP")

#ifdef EMP_ARRAY_H
#define UIT_EMP_ARRAY_H_HEADERGUARD
#endif // #ifdef EMP_ARRAY_H
#pragma pop_macro("EMP_ARRAY_H")

#ifdef EMP_ASSERT_HPP
#define UIT_EMP_ASSERT_HPP_HEADERGUARD
#endif // #ifdef EMP_ASSERT_HPP
#pragma pop_macro("EMP_ASSERT_HPP")

#ifdef EMP_ASSERT_TRIGGER_HPP
#define UIT_EMP_ASSERT_TRIGGER_HPP_HEADERGUARD
#endif // #ifdef EMP_ASSERT_TRIGGER_HPP
#pragma pop_macro("EMP_ASSERT_TRIGGER_HPP")

#ifdef EMP_ASSOCIATIVE_ARRAY_CACHE_HPP
#define UIT_EMP_ASSOCIATIVE_ARRAY_CACHE_HPP_HEADERGUARD
#endif // #ifdef EMP_ASSOCIATIVE_ARRAY_CACHE_HPP
#pragma pop_macro("EMP_ASSOCIATIVE_ARRAY_CACHE_HPP")

#ifdef EMP_BASE_EMP_NAMESPACE_HPP
#define UIT_EMP_BASE_EMP_NAMESPACE_HPP_HEADERGUARD
#endif // #ifdef EMP_BASE_EMP_NAMESPACE_HPP
#pragma pop_macro("EMP_BASE_EMP_NAMESPACE_HPP")

#ifdef EMP_BITSET_UTILS_H
#define UIT_EMP_BITSET_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_BITSET_UTILS_H
#pragma pop_macro("EMP_BITSET_UTILS_H")

#ifdef EMP_BIT_SET_HPP
#define UIT_EMP_BIT_SET_HPP_HEADERGUARD
#endif // #ifdef EMP_BIT_SET_HPP
#pragma pop_macro("EMP_BIT_SET_HPP")

#ifdef EMP_BIT_VECTOR_H
#define UIT_EMP_BIT_VECTOR_H_HEADERGUARD
#endif // #ifdef EMP_BIT_VECTOR_H
#pragma pop_macro("EMP_BIT_VECTOR_H")

#ifdef EMP_CACHE_H
#define UIT_EMP_CACHE_H_HEADERGUARD
#endif // #ifdef EMP_CACHE_H
#pragma pop_macro("EMP_CACHE_H")

#ifdef EMP_CONFIG_H
#define UIT_EMP_CONFIG_H_HEADERGUARD
#endif // #ifdef EMP_CONFIG_H
#pragma pop_macro("EMP_CONFIG_H")

#ifdef EMP_CONFIG_MANAGER_H
#define UIT_EMP_CONFIG_MANAGER_H_HEADERGUARD
#endif // #ifdef EMP_CONFIG_MANAGER_H
#pragma pop_macro("EMP_CONFIG_MANAGER_H")

#ifdef EMP_CONST_H
#define UIT_EMP_CONST_H_HEADERGUARD
#endif // #ifdef EMP_CONST_H
#pragma pop_macro("EMP_CONST_H")

#ifdef EMP_CONTIGUOUS_STREAM_H
#define UIT_EMP_CONTIGUOUS_STREAM_H_HEADERGUARD
#endif // #ifdef EMP_CONTIGUOUS_STREAM_H
#pragma pop_macro("EMP_CONTIGUOUS_STREAM_H")

#ifdef EMP_DATA_FILE_H
#define UIT_EMP_DATA_FILE_H_HEADERGUARD
#endif // #ifdef EMP_DATA_FILE_H
#pragma pop_macro("EMP_DATA_FILE_H")

#ifdef EMP_DATA_NODE_H
#define UIT_EMP_DATA_NODE_H_HEADERGUARD
#endif // #ifdef EMP_DATA_NODE_H
#pragma pop_macro("EMP_DATA_NODE_H")

#ifdef EMP_DEPOSITORY_ENTRY_HPP
#define UIT_EMP_DEPOSITORY_ENTRY_HPP_HEADERGUARD
#endif // #ifdef EMP_DEPOSITORY_ENTRY_HPP
#pragma pop_macro("EMP_DEPOSITORY_ENTRY_HPP")

#ifdef EMP_DISTRIBUTION_H
#define UIT_EMP_DISTRIBUTION_H_HEADERGUARD
#endif // #ifdef EMP_DISTRIBUTION_H
#pragma pop_macro("EMP_DISTRIBUTION_H")

#ifdef EMP_ERRORS_H
#define UIT_EMP_ERRORS_H_HEADERGUARD
#endif // #ifdef EMP_ERRORS_H
#pragma pop_macro("EMP_ERRORS_H")

#ifdef EMP_FUNCTION_SET_H
#define UIT_EMP_FUNCTION_SET_H_HEADERGUARD
#endif // #ifdef EMP_FUNCTION_SET_H
#pragma pop_macro("EMP_FUNCTION_SET_H")

#ifdef EMP_HASH_NAMIFY_H
#define UIT_EMP_HASH_NAMIFY_H_HEADERGUARD
#endif // #ifdef EMP_HASH_NAMIFY_H
#pragma pop_macro("EMP_HASH_NAMIFY_H")

#ifdef EMP_HASH_UTILS_H
#define UIT_EMP_HASH_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_HASH_UTILS_H
#pragma pop_macro("EMP_HASH_UTILS_H")

#ifdef EMP_INDEX_MAP_H
#define UIT_EMP_INDEX_MAP_H_HEADERGUARD
#endif // #ifdef EMP_INDEX_MAP_H
#pragma pop_macro("EMP_INDEX_MAP_H")

#ifdef EMP_IS_STREAMABLE_HPP
#define UIT_EMP_IS_STREAMABLE_HPP_HEADERGUARD
#endif // #ifdef EMP_IS_STREAMABLE_HPP
#pragma pop_macro("EMP_IS_STREAMABLE_HPP")

#ifdef EMP_KEY_NAME_UTILS_H
#define UIT_EMP_KEY_NAME_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_KEY_NAME_UTILS_H
#pragma pop_macro("EMP_KEY_NAME_UTILS_H")

#ifdef EMP_MACROS_H
#define UIT_EMP_MACROS_H_HEADERGUARD
#endif // #ifdef EMP_MACROS_H
#pragma pop_macro("EMP_MACROS_H")

#ifdef EMP_MACRO_MATH_H
#define UIT_EMP_MACRO_MATH_H_HEADERGUARD
#endif // #ifdef EMP_MACRO_MATH_H
#pragma pop_macro("EMP_MACRO_MATH_H")

#ifdef EMP_MAP_H
#define UIT_EMP_MAP_H_HEADERGUARD
#endif // #ifdef EMP_MAP_H
#pragma pop_macro("EMP_MAP_H")

#ifdef EMP_MAP_PROXY_H
#define UIT_EMP_MAP_PROXY_H_HEADERGUARD
#endif // #ifdef EMP_MAP_PROXY_H
#pragma pop_macro("EMP_MAP_PROXY_H")

#ifdef EMP_MAP_UTILS_H
#define UIT_EMP_MAP_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_MAP_UTILS_H
#pragma pop_macro("EMP_MAP_UTILS_H")

#ifdef EMP_MATCH_BIN_METRICS_H
#define UIT_EMP_MATCH_BIN_METRICS_H_HEADERGUARD
#endif // #ifdef EMP_MATCH_BIN_METRICS_H
#pragma pop_macro("EMP_MATCH_BIN_METRICS_H")

#ifdef EMP_MATCH_DEPOSITORY_HPP
#define UIT_EMP_MATCH_DEPOSITORY_HPP_HEADERGUARD
#endif // #ifdef EMP_MATCH_DEPOSITORY_HPP
#pragma pop_macro("EMP_MATCH_DEPOSITORY_HPP")

#ifdef EMP_MATH_H
#define UIT_EMP_MATH_H_HEADERGUARD
#endif // #ifdef EMP_MATH_H
#pragma pop_macro("EMP_MATH_H")

#ifdef EMP_META_H
#define UIT_EMP_META_H_HEADERGUARD
#endif // #ifdef EMP_META_H
#pragma pop_macro("EMP_META_H")

#ifdef EMP_NATIVE_ASSERT_TRIGGER_HPP
#define UIT_EMP_NATIVE_ASSERT_TRIGGER_HPP_HEADERGUARD
#endif // #ifdef EMP_NATIVE_ASSERT_TRIGGER_HPP
#pragma pop_macro("EMP_NATIVE_ASSERT_TRIGGER_HPP")

#ifdef EMP_NULLSTREAM_H
#define UIT_EMP_NULLSTREAM_H_HEADERGUARD
#endif // #ifdef EMP_NULLSTREAM_H
#pragma pop_macro("EMP_NULLSTREAM_H")

#ifdef EMP_OPTIONAL_H
#define UIT_EMP_OPTIONAL_H_HEADERGUARD
#endif // #ifdef EMP_OPTIONAL_H
#pragma pop_macro("EMP_OPTIONAL_H")

#ifdef EMP_PLUS_COUNTDOWN_REGULATOR_HPP
#define UIT_EMP_PLUS_COUNTDOWN_REGULATOR_HPP_HEADERGUARD
#endif // #ifdef EMP_PLUS_COUNTDOWN_REGULATOR_HPP
#pragma pop_macro("EMP_PLUS_COUNTDOWN_REGULATOR_HPP")

#ifdef EMP_PTR_H
#define UIT_EMP_PTR_H_HEADERGUARD
#endif // #ifdef EMP_PTR_H
#pragma pop_macro("EMP_PTR_H")

#ifdef EMP_QUEUECACHE_H
#define UIT_EMP_QUEUECACHE_H_HEADERGUARD
#endif // #ifdef EMP_QUEUECACHE_H
#pragma pop_macro("EMP_QUEUECACHE_H")

#ifdef EMP_RANDOM_H
#define UIT_EMP_RANDOM_H_HEADERGUARD
#endif // #ifdef EMP_RANDOM_H
#pragma pop_macro("EMP_RANDOM_H")

#ifdef EMP_RANDOM_UTILS_H
#define UIT_EMP_RANDOM_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_RANDOM_UTILS_H
#pragma pop_macro("EMP_RANDOM_UTILS_H")

#ifdef EMP_RANGE_H
#define UIT_EMP_RANGE_H_HEADERGUARD
#endif // #ifdef EMP_RANGE_H
#pragma pop_macro("EMP_RANGE_H")

#ifdef EMP_RANKED_SELECTOR_HPP
#define UIT_EMP_RANKED_SELECTOR_HPP_HEADERGUARD
#endif // #ifdef EMP_RANKED_SELECTOR_HPP
#pragma pop_macro("EMP_RANKED_SELECTOR_HPP")

#ifdef EMP_REFLECTION_H
#define UIT_EMP_REFLECTION_H_HEADERGUARD
#endif // #ifdef EMP_REFLECTION_H
#pragma pop_macro("EMP_REFLECTION_H")

#ifdef EMP_SMALL_VECTOR_HPP
#define UIT_EMP_SMALL_VECTOR_HPP_HEADERGUARD
#endif // #ifdef EMP_SMALL_VECTOR_HPP
#pragma pop_macro("EMP_SMALL_VECTOR_HPP")

#ifdef EMP_STRING_TYPE_H
#define UIT_EMP_STRING_TYPE_H_HEADERGUARD
#endif // #ifdef EMP_STRING_TYPE_H
#pragma pop_macro("EMP_STRING_TYPE_H")

#ifdef EMP_STRING_UTILS_H
#define UIT_EMP_STRING_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_STRING_UTILS_H
#pragma pop_macro("EMP_STRING_UTILS_H")

#ifdef EMP_TUPLE_UTILS_H
#define UIT_EMP_TUPLE_UTILS_H_HEADERGUARD
#endif // #ifdef EMP_TUPLE_UTILS_H
#pragma pop_macro("EMP_TUPLE_UTILS_H")

#ifdef EMP_TYPE_ID_H
#define UIT_EMP_TYPE_ID_H_HEADERGUARD
#endif // #ifdef EMP_TYPE_ID_H
#pragma pop_macro("EMP_TYPE_ID_H")

#ifdef EMP_TYPE_PACK_H
#define UIT_EMP_TYPE_PACK_H_HEADERGUARD
#endif // #ifdef EMP_TYPE_PACK_H
#pragma pop_macro("EMP_TYPE_PACK_H")

#ifdef EMP_TYPE_TRAITS_H
#define UIT_EMP_TYPE_TRAITS_H_HEADERGUARD
#endif // #ifdef EMP_TYPE_TRAITS_H
#pragma pop_macro("EMP_TYPE_TRAITS_H")

#ifdef EMP_UNORDERED_INDEX_MAP_H
#define UIT_EMP_UNORDERED_INDEX_MAP_H_HEADERGUARD
#endif // #ifdef EMP_UNORDERED_INDEX_MAP_H
#pragma pop_macro("EMP_UNORDERED_INDEX_MAP_H")

#ifdef EMP_UNORDERED_MAP_H
#define UIT_EMP_UNORDERED_MAP_H_HEADERGUARD
#endif // #ifdef EMP_UNORDERED_MAP_H
#pragma pop_macro("EMP_UNORDERED_MAP_H")

#ifdef EMP_VAL_PACK_H
#define UIT_EMP_VAL_PACK_H_HEADERGUARD
#endif // #ifdef EMP_VAL_PACK_H
#pragma pop_macro("EMP_VAL_PACK_H")

#ifdef EMP_VECTOR_H
#define UIT_EMP_VECTOR_H_HEADERGUARD
#endif // #ifdef EMP_VECTOR_H
#pragma pop_macro("EMP_VECTOR_H")

#endif // #ifdef UIT_VENDORIZE_EMP
