#ifdef UIT_VENDORIZE_EMP

#ifdef EMP_ALWAYS_ASSERT_HPP
#define UIT_EMP_ALWAYS_ASSERT_HPP_HEADERGUARD
#endif // #ifdef EMP_ALWAYS_ASSERT_HPP
#pragma pop_macro("EMP_ALWAYS_ASSERT_HPP")

#ifdef EMP_ASSERT_HPP
#define UIT_EMP_ASSERT_HPP_HEADERGUARD
#endif // #ifdef EMP_ASSERT_HPP
#pragma pop_macro("EMP_ASSERT_HPP")

#ifdef EMP_ASSERT_TRIGGER_HPP
#define UIT_EMP_ASSERT_TRIGGER_HPP_HEADERGUARD
#endif // #ifdef EMP_ASSERT_TRIGGER_HPP
#pragma pop_macro("EMP_ASSERT_TRIGGER_HPP")

#ifdef EMP_BASE_EMP_NAMESPACE_HPP
#define UIT_EMP_BASE_EMP_NAMESPACE_HPP_HEADERGUARD
#endif // #ifdef EMP_BASE_EMP_NAMESPACE_HPP
#pragma pop_macro("EMP_BASE_EMP_NAMESPACE_HPP")

#ifdef EMP_IS_STREAMABLE_HPP
#define UIT_EMP_IS_STREAMABLE_HPP_HEADERGUARD
#endif // #ifdef EMP_IS_STREAMABLE_HPP
#pragma pop_macro("EMP_IS_STREAMABLE_HPP")

#ifdef EMP_MACROS_H
#define UIT_EMP_MACROS_H_HEADERGUARD
#endif // #ifdef EMP_MACROS_H
#pragma pop_macro("EMP_MACROS_H")

#ifdef EMP_MACRO_MATH_H
#define UIT_EMP_MACRO_MATH_H_HEADERGUARD
#endif // #ifdef EMP_MACRO_MATH_H
#pragma pop_macro("EMP_MACRO_MATH_H")

#ifdef EMP_NATIVE_ASSERT_TRIGGER_HPP
#define UIT_EMP_NATIVE_ASSERT_TRIGGER_HPP_HEADERGUARD
#endif // #ifdef EMP_NATIVE_ASSERT_TRIGGER_HPP
#pragma pop_macro("EMP_NATIVE_ASSERT_TRIGGER_HPP")

#endif // #ifdef UIT_VENDORIZE_EMP
