#ifdef UIT_VENDORIZE_EMP

#pragma push_macro("EMP_POINT_2D_H")
#ifndef UIT_EMP_POINT_2D_H_HEADERGUARD
#undef EMP_POINT_2D_H
#endif // #ifndef UIT_EMP_POINT_2D_H_HEADERGUARD

#pragma push_macro("EMP_ANGLE_2D_H")
#ifndef UIT_EMP_ANGLE_2D_H_HEADERGUARD
#undef EMP_ANGLE_2D_H
#endif // #ifndef UIT_EMP_ANGLE_2D_H_HEADERGUARD

#pragma push_macro("EMP_SURFACE_2D_H")
#ifndef UIT_EMP_SURFACE_2D_H_HEADERGUARD
#undef EMP_SURFACE_2D_H
#endif // #ifndef UIT_EMP_SURFACE_2D_H_HEADERGUARD

#pragma push_macro("EMP_CIRCLE_2D_H")
#ifndef UIT_EMP_CIRCLE_2D_H_HEADERGUARD
#undef EMP_CIRCLE_2D_H
#endif // #ifndef UIT_EMP_CIRCLE_2D_H_HEADERGUARD

#pragma push_macro("EMP_BODY_2D_H")
#ifndef UIT_EMP_BODY_2D_H_HEADERGUARD
#undef EMP_BODY_2D_H
#endif // #ifndef UIT_EMP_BODY_2D_H_HEADERGUARD

#pragma push_macro("EMP_SURFACE2_H")
#ifndef UIT_EMP_SURFACE2_H_HEADERGUARD
#undef EMP_SURFACE2_H
#endif // #ifndef UIT_EMP_SURFACE2_H_HEADERGUARD

#pragma push_macro("EMP_PHYSICS_2D_H")
#ifndef UIT_EMP_PHYSICS_2D_H_HEADERGUARD
#undef EMP_PHYSICS_2D_H
#endif // #ifndef UIT_EMP_PHYSICS_2D_H_HEADERGUARD

#pragma push_macro("EMP_DATA_MAP_H")
#ifndef UIT_EMP_DATA_MAP_H_HEADERGUARD
#undef EMP_DATA_MAP_H
#endif // #ifndef UIT_EMP_DATA_MAP_H_HEADERGUARD

#pragma push_macro("EMP_DATA_TRAIT_H")
#ifndef UIT_EMP_DATA_TRAIT_H_HEADERGUARD
#undef EMP_DATA_TRAIT_H
#endif // #ifndef UIT_EMP_DATA_TRAIT_H_HEADERGUARD

#pragma push_macro("EMP_DATA_NODE_H")
#ifndef UIT_EMP_DATA_NODE_H_HEADERGUARD
#undef EMP_DATA_NODE_H
#endif // #ifndef UIT_EMP_DATA_NODE_H_HEADERGUARD

#pragma push_macro("EMP_VAR_MAP_H")
#ifndef UIT_EMP_VAR_MAP_H_HEADERGUARD
#undef EMP_VAR_MAP_H
#endif // #ifndef UIT_EMP_VAR_MAP_H_HEADERGUARD

#pragma push_macro("EMP_DATA_FILE_H")
#ifndef UIT_EMP_DATA_FILE_H_HEADERGUARD
#undef EMP_DATA_FILE_H
#endif // #ifndef UIT_EMP_DATA_FILE_H_HEADERGUARD

#pragma push_macro("EMP_MEMORY_IMAGE_H")
#ifndef UIT_EMP_MEMORY_IMAGE_H_HEADERGUARD
#undef EMP_MEMORY_IMAGE_H
#endif // #ifndef UIT_EMP_MEMORY_IMAGE_H_HEADERGUARD

#pragma push_macro("EMP_DATA_INTERFACE_H")
#ifndef UIT_EMP_DATA_INTERFACE_H_HEADERGUARD
#undef EMP_DATA_INTERFACE_H
#endif // #ifndef UIT_EMP_DATA_INTERFACE_H_HEADERGUARD

#pragma push_macro("EMP_DATA_MANAGER_H")
#ifndef UIT_EMP_DATA_MANAGER_H_HEADERGUARD
#undef EMP_DATA_MANAGER_H
#endif // #ifndef UIT_EMP_DATA_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_DATA_LOG_H")
#ifndef UIT_EMP_DATA_LOG_H_HEADERGUARD
#undef EMP_DATA_LOG_H
#endif // #ifndef UIT_EMP_DATA_LOG_H_HEADERGUARD

#pragma push_macro("EMP_DATA_LAYOUT_H")
#ifndef UIT_EMP_DATA_LAYOUT_H_HEADERGUARD
#undef EMP_DATA_LAYOUT_H
#endif // #ifndef UIT_EMP_DATA_LAYOUT_H_HEADERGUARD

#pragma push_macro("EMP_REGEX_H")
#ifndef UIT_EMP_REGEX_H_HEADERGUARD
#undef EMP_REGEX_H
#endif // #ifndef UIT_EMP_REGEX_H_HEADERGUARD

#pragma push_macro("EMP_LEXER_UTILS_H")
#ifndef UIT_EMP_LEXER_UTILS_H_HEADERGUARD
#undef EMP_LEXER_UTILS_H
#endif // #ifndef UIT_EMP_LEXER_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_NFA_H")
#ifndef UIT_EMP_NFA_H_HEADERGUARD
#undef EMP_NFA_H
#endif // #ifndef UIT_EMP_NFA_H_HEADERGUARD

#pragma push_macro("EMP_LEXER_H")
#ifndef UIT_EMP_LEXER_H_HEADERGUARD
#undef EMP_LEXER_H
#endif // #ifndef UIT_EMP_LEXER_H_HEADERGUARD

#pragma push_macro("EMP_DFA_H")
#ifndef UIT_EMP_DFA_H_HEADERGUARD
#undef EMP_DFA_H
#endif // #ifndef UIT_EMP_DFA_H_HEADERGUARD

#pragma push_macro("EMP_SETTING_CONFIG_H")
#ifndef UIT_EMP_SETTING_CONFIG_H_HEADERGUARD
#undef EMP_SETTING_CONFIG_H
#endif // #ifndef UIT_EMP_SETTING_CONFIG_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_WEB_INTERFACE_H")
#ifndef UIT_EMP_CONFIG_WEB_INTERFACE_H_HEADERGUARD
#undef EMP_CONFIG_WEB_INTERFACE_H
#endif // #ifndef UIT_EMP_CONFIG_WEB_INTERFACE_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_UTILS_H")
#ifndef UIT_EMP_CONFIG_UTILS_H_HEADERGUARD
#undef EMP_CONFIG_UTILS_H
#endif // #ifndef UIT_EMP_CONFIG_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_CL_ARG_MANAGER_H")
#ifndef UIT_EMP_CL_ARG_MANAGER_H_HEADERGUARD
#undef EMP_CL_ARG_MANAGER_H
#endif // #ifndef UIT_EMP_CL_ARG_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_H")
#ifndef UIT_EMP_CONFIG_H_HEADERGUARD
#undef EMP_CONFIG_H
#endif // #ifndef UIT_EMP_CONFIG_H_HEADERGUARD

#pragma push_macro("EMP_COMMAND_LINE_H")
#ifndef UIT_EMP_COMMAND_LINE_H_HEADERGUARD
#undef EMP_COMMAND_LINE_H
#endif // #ifndef UIT_EMP_COMMAND_LINE_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_MANAGER_H")
#ifndef UIT_EMP_CONFIG_MANAGER_H_HEADERGUARD
#undef EMP_CONFIG_MANAGER_H
#endif // #ifndef UIT_EMP_CONFIG_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_SETTING_COMBOS_H")
#ifndef UIT_EMP_SETTING_COMBOS_H_HEADERGUARD
#undef EMP_SETTING_COMBOS_H
#endif // #ifndef UIT_EMP_SETTING_COMBOS_H_HEADERGUARD

#pragma push_macro("EMP_BITSET_UTILS_H")
#ifndef UIT_EMP_BITSET_UTILS_H_HEADERGUARD
#undef EMP_BITSET_UTILS_H
#endif // #ifndef UIT_EMP_BITSET_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_BIT_VECTOR_H")
#ifndef UIT_EMP_BIT_VECTOR_H_HEADERGUARD
#undef EMP_BIT_VECTOR_H
#endif // #ifndef UIT_EMP_BIT_VECTOR_H_HEADERGUARD

#pragma push_macro("EMP_BIT_MATRIX_H")
#ifndef UIT_EMP_BIT_MATRIX_H_HEADERGUARD
#undef EMP_BIT_MATRIX_H
#endif // #ifndef UIT_EMP_BIT_MATRIX_H_HEADERGUARD

#pragma push_macro("EMP_RANDOM_UTILS_H")
#ifndef UIT_EMP_RANDOM_UTILS_H_HEADERGUARD
#undef EMP_RANDOM_UTILS_H
#endif // #ifndef UIT_EMP_RANDOM_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_INFO_THEORY_H")
#ifndef UIT_EMP_INFO_THEORY_H_HEADERGUARD
#undef EMP_INFO_THEORY_H
#endif // #ifndef UIT_EMP_INFO_THEORY_H_HEADERGUARD

#pragma push_macro("EMP_DISTRIBUTION_H")
#ifndef UIT_EMP_DISTRIBUTION_H_HEADERGUARD
#undef EMP_DISTRIBUTION_H
#endif // #ifndef UIT_EMP_DISTRIBUTION_H_HEADERGUARD

#pragma push_macro("EMP_COMBOS_H")
#ifndef UIT_EMP_COMBOS_H_HEADERGUARD
#undef EMP_COMBOS_H
#endif // #ifndef UIT_EMP_COMBOS_H_HEADERGUARD

#pragma push_macro("EMP_STATS_H")
#ifndef UIT_EMP_STATS_H_HEADERGUARD
#undef EMP_STATS_H
#endif // #ifndef UIT_EMP_STATS_H_HEADERGUARD

#pragma push_macro("EMP_DISTANCES_H")
#ifndef UIT_EMP_DISTANCES_H_HEADERGUARD
#undef EMP_DISTANCES_H
#endif // #ifndef UIT_EMP_DISTANCES_H_HEADERGUARD

#pragma push_macro("EMP_MATH_H")
#ifndef UIT_EMP_MATH_H_HEADERGUARD
#undef EMP_MATH_H
#endif // #ifndef UIT_EMP_MATH_H_HEADERGUARD

#pragma push_macro("EMP_SPATIAL_STATS_H")
#ifndef UIT_EMP_SPATIAL_STATS_H_HEADERGUARD
#undef EMP_SPATIAL_STATS_H
#endif // #ifndef UIT_EMP_SPATIAL_STATS_H_HEADERGUARD

#pragma push_macro("EMP_RANGE_H")
#ifndef UIT_EMP_RANGE_H_HEADERGUARD
#undef EMP_RANGE_H
#endif // #ifndef UIT_EMP_RANGE_H_HEADERGUARD

#pragma push_macro("EMP_SEQUENCE_UTILS_H")
#ifndef UIT_EMP_SEQUENCE_UTILS_H_HEADERGUARD
#undef EMP_SEQUENCE_UTILS_H
#endif // #ifndef UIT_EMP_SEQUENCE_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_RANDOM_H")
#ifndef UIT_EMP_RANDOM_H_HEADERGUARD
#undef EMP_RANDOM_H
#endif // #ifndef UIT_EMP_RANDOM_H_HEADERGUARD

#pragma push_macro("EMP_CONST_H")
#ifndef UIT_EMP_CONST_H_HEADERGUARD
#undef EMP_CONST_H
#endif // #ifndef UIT_EMP_CONST_H_HEADERGUARD

#pragma push_macro("EMP_EVO_NK_H")
#ifndef UIT_EMP_EVO_NK_H_HEADERGUARD
#undef EMP_EVO_NK_H
#endif // #ifndef UIT_EMP_EVO_NK_H_HEADERGUARD

#pragma push_macro("EMP_OEE_STATS_H")
#ifndef UIT_EMP_OEE_STATS_H_HEADERGUARD
#undef EMP_OEE_STATS_H
#endif // #ifndef UIT_EMP_OEE_STATS_H_HEADERGUARD

#pragma push_macro("EMP_ORG_INTERFACE_H")
#ifndef UIT_EMP_ORG_INTERFACE_H_HEADERGUARD
#undef EMP_ORG_INTERFACE_H
#endif // #ifndef UIT_EMP_ORG_INTERFACE_H_HEADERGUARD

#pragma push_macro("EMP_EVO_NK_CONST_H")
#ifndef UIT_EMP_EVO_NK_CONST_H_HEADERGUARD
#undef EMP_EVO_NK_CONST_H
#endif // #ifndef UIT_EMP_EVO_NK_CONST_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_SELECT_H")
#ifndef UIT_EMP_EVO_WORLD_SELECT_H_HEADERGUARD
#undef EMP_EVO_WORLD_SELECT_H
#endif // #ifndef UIT_EMP_EVO_WORLD_SELECT_H_HEADERGUARD

#pragma push_macro("EMP_EVO_STATE_GRID_H")
#ifndef UIT_EMP_EVO_STATE_GRID_H_HEADERGUARD
#undef EMP_EVO_STATE_GRID_H
#endif // #ifndef UIT_EMP_EVO_STATE_GRID_H_HEADERGUARD

#pragma push_macro("EMP_EVO_RESOURCE_H")
#ifndef UIT_EMP_EVO_RESOURCE_H_HEADERGUARD
#undef EMP_EVO_RESOURCE_H
#endif // #ifndef UIT_EMP_EVO_RESOURCE_H_HEADERGUARD

#pragma push_macro("EMP_EVO_SYSTEMATICS_H")
#ifndef UIT_EMP_EVO_SYSTEMATICS_H_HEADERGUARD
#undef EMP_EVO_SYSTEMATICS_H
#endif // #ifndef UIT_EMP_EVO_SYSTEMATICS_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_OUTPUT_H")
#ifndef UIT_EMP_EVO_WORLD_OUTPUT_H_HEADERGUARD
#undef EMP_EVO_WORLD_OUTPUT_H
#endif // #ifndef UIT_EMP_EVO_WORLD_OUTPUT_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_ITER_H")
#ifndef UIT_EMP_EVO_WORLD_ITER_H_HEADERGUARD
#undef EMP_EVO_WORLD_ITER_H
#endif // #ifndef UIT_EMP_EVO_WORLD_ITER_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_STRUCTURE_H")
#ifndef UIT_EMP_EVO_WORLD_STRUCTURE_H_HEADERGUARD
#undef EMP_EVO_WORLD_STRUCTURE_H
#endif // #ifndef UIT_EMP_EVO_WORLD_STRUCTURE_H_HEADERGUARD

#pragma push_macro("EMP_EVO_SYSTEMATICS_ANALYSIS_H")
#ifndef UIT_EMP_EVO_SYSTEMATICS_ANALYSIS_H_HEADERGUARD
#undef EMP_EVO_SYSTEMATICS_ANALYSIS_H
#endif // #ifndef UIT_EMP_EVO_SYSTEMATICS_ANALYSIS_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_REFLECT_H")
#ifndef UIT_EMP_EVO_WORLD_REFLECT_H_HEADERGUARD
#undef EMP_EVO_WORLD_REFLECT_H
#endif // #ifndef UIT_EMP_EVO_WORLD_REFLECT_H_HEADERGUARD

#pragma push_macro("EMP_EVO_WORLD_H")
#ifndef UIT_EMP_EVO_WORLD_H_HEADERGUARD
#undef EMP_EVO_WORLD_H
#endif // #ifndef UIT_EMP_EVO_WORLD_H_HEADERGUARD

#pragma push_macro("EMP_TRAIT_H")
#ifndef UIT_EMP_TRAIT_H_HEADERGUARD
#undef EMP_TRAIT_H
#endif // #ifndef UIT_EMP_TRAIT_H_HEADERGUARD

#pragma push_macro("EMP_PARSER_H")
#ifndef UIT_EMP_PARSER_H_HEADERGUARD
#undef EMP_PARSER_H
#endif // #ifndef UIT_EMP_PARSER_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_LEXER_H")
#ifndef UIT_EMP_CONFIG_LEXER_H_HEADERGUARD
#undef EMP_CONFIG_LEXER_H
#endif // #ifndef UIT_EMP_CONFIG_LEXER_H_HEADERGUARD

#pragma push_macro("EMP_BATCH_CONFIG_H")
#ifndef UIT_EMP_BATCH_CONFIG_H_HEADERGUARD
#undef EMP_BATCH_CONFIG_H
#endif // #ifndef UIT_EMP_BATCH_CONFIG_H_HEADERGUARD

#pragma push_macro("EMP_CONFIG_PARSER_H")
#ifndef UIT_EMP_CONFIG_PARSER_H_HEADERGUARD
#undef EMP_CONFIG_PARSER_H
#endif // #ifndef UIT_EMP_CONFIG_PARSER_H_HEADERGUARD

#pragma push_macro("EMP_CLASS_H")
#ifndef UIT_EMP_CLASS_H_HEADERGUARD
#undef EMP_CLASS_H
#endif // #ifndef UIT_EMP_CLASS_H_HEADERGUARD

#pragma push_macro("EMP_STRUCT_H")
#ifndef UIT_EMP_STRUCT_H_HEADERGUARD
#undef EMP_STRUCT_H
#endif // #ifndef UIT_EMP_STRUCT_H_HEADERGUARD

#pragma push_macro("EMP_FIXED_H")
#ifndef UIT_EMP_FIXED_H_HEADERGUARD
#undef EMP_FIXED_H
#endif // #ifndef UIT_EMP_FIXED_H_HEADERGUARD

#pragma push_macro("EMP_CE_STRING_H")
#ifndef UIT_EMP_CE_STRING_H_HEADERGUARD
#undef EMP_CE_STRING_H
#endif // #ifndef UIT_EMP_CE_STRING_H_HEADERGUARD

#pragma push_macro("EMP_CE_ARRAY_H")
#ifndef UIT_EMP_CE_ARRAY_H_HEADERGUARD
#undef EMP_CE_ARRAY_H
#endif // #ifndef UIT_EMP_CE_ARRAY_H_HEADERGUARD

#pragma push_macro("EMP_CE_RANDOM_H")
#ifndef UIT_EMP_CE_RANDOM_H_HEADERGUARD
#undef EMP_CE_RANDOM_H
#endif // #ifndef UIT_EMP_CE_RANDOM_H_HEADERGUARD

#pragma push_macro("EMP_VAR_H")
#ifndef UIT_EMP_VAR_H_HEADERGUARD
#undef EMP_VAR_H
#endif // #ifndef UIT_EMP_VAR_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_TYPE_H")
#ifndef UIT_EMP_EMPOWER_TYPE_H_HEADERGUARD
#undef EMP_EMPOWER_TYPE_H
#endif // #ifndef UIT_EMP_EMPOWER_TYPE_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_H")
#ifndef UIT_EMP_EMPOWER_H_HEADERGUARD
#undef EMP_EMPOWER_H
#endif // #ifndef UIT_EMP_EMPOWER_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_TYPE_MANAGER_H")
#ifndef UIT_EMP_EMPOWER_TYPE_MANAGER_H_HEADERGUARD
#undef EMP_EMPOWER_TYPE_MANAGER_H
#endif // #ifndef UIT_EMP_EMPOWER_TYPE_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_MEMORY_IMAGE_H")
#ifndef UIT_EMP_MEMORY_IMAGE_H_HEADERGUARD
#undef EMP_MEMORY_IMAGE_H
#endif // #ifndef UIT_EMP_MEMORY_IMAGE_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_VAR_INFO_H")
#ifndef UIT_EMP_EMPOWER_VAR_INFO_H_HEADERGUARD
#undef EMP_EMPOWER_VAR_INFO_H
#endif // #ifndef UIT_EMP_EMPOWER_VAR_INFO_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_VAR_H")
#ifndef UIT_EMP_EMPOWER_VAR_H_HEADERGUARD
#undef EMP_EMPOWER_VAR_H
#endif // #ifndef UIT_EMP_EMPOWER_VAR_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_STRUCT_H")
#ifndef UIT_EMP_EMPOWER_STRUCT_H_HEADERGUARD
#undef EMP_EMPOWER_STRUCT_H
#endif // #ifndef UIT_EMP_EMPOWER_STRUCT_H_HEADERGUARD

#pragma push_macro("EMP_EMPOWER_STRUCT_TYPE_H")
#ifndef UIT_EMP_EMPOWER_STRUCT_TYPE_H_HEADERGUARD
#undef EMP_EMPOWER_STRUCT_TYPE_H
#endif // #ifndef UIT_EMP_EMPOWER_STRUCT_TYPE_H_HEADERGUARD

#pragma push_macro("EMP_VECTOR_H")
#ifndef UIT_EMP_VECTOR_H_HEADERGUARD
#undef EMP_VECTOR_H
#endif // #ifndef UIT_EMP_VECTOR_H_HEADERGUARD

#pragma push_macro("EMP_ARRAY_H")
#ifndef UIT_EMP_ARRAY_H_HEADERGUARD
#undef EMP_ARRAY_H
#endif // #ifndef UIT_EMP_ARRAY_H_HEADERGUARD

#pragma push_macro("EMP_PTR_H")
#ifndef UIT_EMP_PTR_H_HEADERGUARD
#undef EMP_PTR_H
#endif // #ifndef UIT_EMP_PTR_H_HEADERGUARD

#pragma push_macro("EMP_MAP_H")
#ifndef UIT_EMP_MAP_H_HEADERGUARD
#undef EMP_MAP_H
#endif // #ifndef UIT_EMP_MAP_H_HEADERGUARD

#pragma push_macro("EMP_ERRORS_H")
#ifndef UIT_EMP_ERRORS_H_HEADERGUARD
#undef EMP_ERRORS_H
#endif // #ifndef UIT_EMP_ERRORS_H_HEADERGUARD

#pragma push_macro("EMP_MAP_PROXY_H")
#ifndef UIT_EMP_MAP_PROXY_H_HEADERGUARD
#undef EMP_MAP_PROXY_H
#endif // #ifndef UIT_EMP_MAP_PROXY_H_HEADERGUARD

#pragma push_macro("EMP_MACROS_H")
#ifndef UIT_EMP_MACROS_H_HEADERGUARD
#undef EMP_MACROS_H
#endif // #ifndef UIT_EMP_MACROS_H_HEADERGUARD

#pragma push_macro("EMP_OPTIONAL_H")
#ifndef UIT_EMP_OPTIONAL_H_HEADERGUARD
#undef EMP_OPTIONAL_H
#endif // #ifndef UIT_EMP_OPTIONAL_H_HEADERGUARD

#pragma push_macro("EMP_MACRO_MATH_H")
#ifndef UIT_EMP_MACRO_MATH_H_HEADERGUARD
#undef EMP_MACRO_MATH_H
#endif // #ifndef UIT_EMP_MACRO_MATH_H_HEADERGUARD

#pragma push_macro("EMP_UNORDERED_MAP_H")
#ifndef UIT_EMP_UNORDERED_MAP_H_HEADERGUARD
#undef EMP_UNORDERED_MAP_H
#endif // #ifndef UIT_EMP_UNORDERED_MAP_H_HEADERGUARD

#pragma push_macro("EMP_UNIT_TESTS_H")
#ifndef UIT_EMP_UNIT_TESTS_H_HEADERGUARD
#undef EMP_UNIT_TESTS_H
#endif // #ifndef UIT_EMP_UNIT_TESTS_H_HEADERGUARD

#pragma push_macro("EMP_GRAPH_UTILS_H")
#ifndef UIT_EMP_GRAPH_UTILS_H_HEADERGUARD
#undef EMP_GRAPH_UTILS_H
#endif // #ifndef UIT_EMP_GRAPH_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_BOOL_H")
#ifndef UIT_EMP_BOOL_H_HEADERGUARD
#undef EMP_BOOL_H
#endif // #ifndef UIT_EMP_BOOL_H_HEADERGUARD

#pragma push_macro("EMP_TYPE_MAP_H")
#ifndef UIT_EMP_TYPE_MAP_H_HEADERGUARD
#undef EMP_TYPE_MAP_H
#endif // #ifndef UIT_EMP_TYPE_MAP_H_HEADERGUARD

#pragma push_macro("EMP_REFERENCE_VECTOR_H")
#ifndef UIT_EMP_REFERENCE_VECTOR_H_HEADERGUARD
#undef EMP_REFERENCE_VECTOR_H
#endif // #ifndef UIT_EMP_REFERENCE_VECTOR_H_HEADERGUARD

#pragma push_macro("EMP_UNORDERED_INDEX_MAP_H")
#ifndef UIT_EMP_UNORDERED_INDEX_MAP_H_HEADERGUARD
#undef EMP_UNORDERED_INDEX_MAP_H
#endif // #ifndef UIT_EMP_UNORDERED_INDEX_MAP_H_HEADERGUARD

#pragma push_macro("EMP_MAP_UTILS_H")
#ifndef UIT_EMP_MAP_UTILS_H_HEADERGUARD
#undef EMP_MAP_UTILS_H
#endif // #ifndef UIT_EMP_MAP_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_GRAPH_H")
#ifndef UIT_EMP_GRAPH_H_HEADERGUARD
#undef EMP_GRAPH_H
#endif // #ifndef UIT_EMP_GRAPH_H_HEADERGUARD

#pragma push_macro("EMP_QUEUECACHE_H")
#ifndef UIT_EMP_QUEUECACHE_H_HEADERGUARD
#undef EMP_QUEUECACHE_H
#endif // #ifndef UIT_EMP_QUEUECACHE_H_HEADERGUARD

#pragma push_macro("EMP_TUPLE_UTILS_H")
#ifndef UIT_EMP_TUPLE_UTILS_H_HEADERGUARD
#undef EMP_TUPLE_UTILS_H
#endif // #ifndef UIT_EMP_TUPLE_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_TIME_QUEUE_H")
#ifndef UIT_EMP_TIME_QUEUE_H_HEADERGUARD
#undef EMP_TIME_QUEUE_H
#endif // #ifndef UIT_EMP_TIME_QUEUE_H_HEADERGUARD

#pragma push_macro("EMP_RA_SET_H")
#ifndef UIT_EMP_RA_SET_H_HEADERGUARD
#undef EMP_RA_SET_H
#endif // #ifndef UIT_EMP_RA_SET_H_HEADERGUARD

#pragma push_macro("EMP_SET_UTILS_H")
#ifndef UIT_EMP_SET_UTILS_H_HEADERGUARD
#undef EMP_SET_UTILS_H
#endif // #ifndef UIT_EMP_SET_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_STRING_MAP_H")
#ifndef UIT_EMP_STRING_MAP_H_HEADERGUARD
#undef EMP_STRING_MAP_H
#endif // #ifndef UIT_EMP_STRING_MAP_H_HEADERGUARD

#pragma push_macro("EMP_VALSORT_MAP_H")
#ifndef UIT_EMP_VALSORT_MAP_H_HEADERGUARD
#undef EMP_VALSORT_MAP_H
#endif // #ifndef UIT_EMP_VALSORT_MAP_H_HEADERGUARD

#pragma push_macro("EMP_DYNAMIC_STRING_H")
#ifndef UIT_EMP_DYNAMIC_STRING_H_HEADERGUARD
#undef EMP_DYNAMIC_STRING_H
#endif // #ifndef UIT_EMP_DYNAMIC_STRING_H_HEADERGUARD

#pragma push_macro("EMP_INDEX_MAP_H")
#ifndef UIT_EMP_INDEX_MAP_H_HEADERGUARD
#undef EMP_INDEX_MAP_H
#endif // #ifndef UIT_EMP_INDEX_MAP_H_HEADERGUARD

#pragma push_macro("EMP_CACHE_H")
#ifndef UIT_EMP_CACHE_H_HEADERGUARD
#undef EMP_CACHE_H
#endif // #ifndef UIT_EMP_CACHE_H_HEADERGUARD

#pragma push_macro("EMP_HASH_UTILS_H")
#ifndef UIT_EMP_HASH_UTILS_H_HEADERGUARD
#undef EMP_HASH_UTILS_H
#endif // #ifndef UIT_EMP_HASH_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_VECTOR_UTILS_H")
#ifndef UIT_EMP_VECTOR_UTILS_H_HEADERGUARD
#undef EMP_VECTOR_UTILS_H
#endif // #ifndef UIT_EMP_VECTOR_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_TUPLE_STRUCT_H")
#ifndef UIT_EMP_TUPLE_STRUCT_H_HEADERGUARD
#undef EMP_TUPLE_STRUCT_H
#endif // #ifndef UIT_EMP_TUPLE_STRUCT_H_HEADERGUARD

#pragma push_macro("EMP_EVENT_DRIVEN_GP_H")
#ifndef UIT_EMP_EVENT_DRIVEN_GP_H_HEADERGUARD
#undef EMP_EVENT_DRIVEN_GP_H
#endif // #ifndef UIT_EMP_EVENT_DRIVEN_GP_H_HEADERGUARD

#pragma push_macro("EMP_INST_LIB_H")
#ifndef UIT_EMP_INST_LIB_H_HEADERGUARD
#undef EMP_INST_LIB_H
#endif // #ifndef UIT_EMP_INST_LIB_H_HEADERGUARD

#pragma push_macro("EMP_SIGNALGP_UTILS_H")
#ifndef UIT_EMP_SIGNALGP_UTILS_H_HEADERGUARD
#undef EMP_SIGNALGP_UTILS_H
#endif // #ifndef UIT_EMP_SIGNALGP_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_BIT_SORTER_H")
#ifndef UIT_EMP_BIT_SORTER_H_HEADERGUARD
#undef EMP_BIT_SORTER_H
#endif // #ifndef UIT_EMP_BIT_SORTER_H_HEADERGUARD

#pragma push_macro("EMP_AVIDA_CPU_INST_LIB_H")
#ifndef UIT_EMP_AVIDA_CPU_INST_LIB_H_HEADERGUARD
#undef EMP_AVIDA_CPU_INST_LIB_H
#endif // #ifndef UIT_EMP_AVIDA_CPU_INST_LIB_H_HEADERGUARD

#pragma push_macro("EMP_LINEAR_CODE_H")
#ifndef UIT_EMP_LINEAR_CODE_H_HEADERGUARD
#undef EMP_LINEAR_CODE_H
#endif // #ifndef UIT_EMP_LINEAR_CODE_H_HEADERGUARD

#pragma push_macro("EMP_EVENT_LIB_H")
#ifndef UIT_EMP_EVENT_LIB_H_HEADERGUARD
#undef EMP_EVENT_LIB_H
#endif // #ifndef UIT_EMP_EVENT_LIB_H_HEADERGUARD

#pragma push_macro("EMP_AVIDA_GP_H")
#ifndef UIT_EMP_AVIDA_GP_H_HEADERGUARD
#undef EMP_AVIDA_GP_H
#endif // #ifndef UIT_EMP_AVIDA_GP_H_HEADERGUARD

#pragma push_macro("EMP_WEB_CANVAS_ACTION_H")
#ifndef UIT_EMP_WEB_CANVAS_ACTION_H_HEADERGUARD
#undef EMP_WEB_CANVAS_ACTION_H
#endif // #ifndef UIT_EMP_WEB_CANVAS_ACTION_H_HEADERGUARD

#pragma push_macro("EMP_WEB_NATIVECANVAS_H")
#ifndef UIT_EMP_WEB_NATIVECANVAS_H_HEADERGUARD
#undef EMP_WEB_NATIVECANVAS_H
#endif // #ifndef UIT_EMP_WEB_NATIVECANVAS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_ELEMENT_H")
#ifndef UIT_EMP_WEB_ELEMENT_H_HEADERGUARD
#undef EMP_WEB_ELEMENT_H
#endif // #ifndef UIT_EMP_WEB_ELEMENT_H_HEADERGUARD

#pragma push_macro("EMP_WEB_IMAGE_H")
#ifndef UIT_EMP_WEB_IMAGE_H_HEADERGUARD
#undef EMP_WEB_IMAGE_H
#endif // #ifndef UIT_EMP_WEB_IMAGE_H_HEADERGUARD

#pragma push_macro("EMP_FONT_H")
#ifndef UIT_EMP_FONT_H_HEADERGUARD
#undef EMP_FONT_H
#endif // #ifndef UIT_EMP_FONT_H_HEADERGUARD

#pragma push_macro("EMP_COLOR_MAP_H")
#ifndef UIT_EMP_COLOR_MAP_H_HEADERGUARD
#undef EMP_COLOR_MAP_H
#endif // #ifndef UIT_EMP_COLOR_MAP_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TWEEN_H")
#ifndef UIT_EMP_WEB_TWEEN_H_HEADERGUARD
#undef EMP_WEB_TWEEN_H
#endif // #ifndef UIT_EMP_WEB_TWEEN_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_H")
#ifndef UIT_EMP_WEB_TABLE_H_HEADERGUARD
#undef EMP_WEB_TABLE_H
#endif // #ifndef UIT_EMP_WEB_TABLE_H_HEADERGUARD

#pragma push_macro("EMP_WEB_SELECTOR_H")
#ifndef UIT_EMP_WEB_SELECTOR_H_HEADERGUARD
#undef EMP_WEB_SELECTOR_H
#endif // #ifndef UIT_EMP_WEB_SELECTOR_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_ROW_H")
#ifndef UIT_EMP_WEB_TABLE_ROW_H_HEADERGUARD
#undef EMP_WEB_TABLE_ROW_H
#endif // #ifndef UIT_EMP_WEB_TABLE_ROW_H_HEADERGUARD

#pragma push_macro("EMP_INIT_H")
#ifndef UIT_EMP_INIT_H_HEADERGUARD
#undef EMP_INIT_H
#endif // #ifndef UIT_EMP_INIT_H_HEADERGUARD

#pragma push_macro("EMP_WEB_EVENTS_H")
#ifndef UIT_EMP_WEB_EVENTS_H_HEADERGUARD
#undef EMP_WEB_EVENTS_H
#endif // #ifndef UIT_EMP_WEB_EVENTS_H_HEADERGUARD

#pragma push_macro("EMP_RAW_IMAGE_H")
#ifndef UIT_EMP_RAW_IMAGE_H_HEADERGUARD
#undef EMP_RAW_IMAGE_H
#endif // #ifndef UIT_EMP_RAW_IMAGE_H_HEADERGUARD

#pragma push_macro("EMP_WEB_COMMANDS_H")
#ifndef UIT_EMP_WEB_COMMANDS_H_HEADERGUARD
#undef EMP_WEB_COMMANDS_H
#endif // #ifndef UIT_EMP_WEB_COMMANDS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_WIDGET_H")
#ifndef UIT_EMP_WEB_WIDGET_H_HEADERGUARD
#undef EMP_WEB_WIDGET_H
#endif // #ifndef UIT_EMP_WEB_WIDGET_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_CELL_H")
#ifndef UIT_EMP_WEB_TABLE_CELL_H_HEADERGUARD
#undef EMP_WEB_TABLE_CELL_H
#endif // #ifndef UIT_EMP_WEB_TABLE_CELL_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_COL_GROUP_H")
#ifndef UIT_EMP_WEB_TABLE_COL_GROUP_H_HEADERGUARD
#undef EMP_WEB_TABLE_COL_GROUP_H
#endif // #ifndef UIT_EMP_WEB_TABLE_COL_GROUP_H_HEADERGUARD

#pragma push_macro("EMP_WEB_KEYPRESS_MANAGER_H")
#ifndef UIT_EMP_WEB_KEYPRESS_MANAGER_H_HEADERGUARD
#undef EMP_WEB_KEYPRESS_MANAGER_H
#endif // #ifndef UIT_EMP_WEB_KEYPRESS_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_JSWRAP_H")
#ifndef UIT_EMP_JSWRAP_H_HEADERGUARD
#undef EMP_JSWRAP_H
#endif // #ifndef UIT_EMP_JSWRAP_H_HEADERGUARD

#pragma push_macro("EMP_WEB_WIDGET_EXTRA_H")
#ifndef UIT_EMP_WEB_WIDGET_EXTRA_H_HEADERGUARD
#undef EMP_WEB_WIDGET_EXTRA_H
#endif // #ifndef UIT_EMP_WEB_WIDGET_EXTRA_H_HEADERGUARD

#pragma push_macro("EMP_WEB_CANVAS_UTILS_H")
#ifndef UIT_EMP_WEB_CANVAS_UTILS_H_HEADERGUARD
#undef EMP_WEB_CANVAS_UTILS_H
#endif // #ifndef UIT_EMP_WEB_CANVAS_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_JS_UTILS_H")
#ifndef UIT_EMP_JS_UTILS_H_HEADERGUARD
#undef EMP_JS_UTILS_H
#endif // #ifndef UIT_EMP_JS_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_ANIMATE_H")
#ifndef UIT_EMP_WEB_ANIMATE_H_HEADERGUARD
#undef EMP_WEB_ANIMATE_H
#endif // #ifndef UIT_EMP_WEB_ANIMATE_H_HEADERGUARD

#pragma push_macro("EMP_WEB_DOCUEXTRAS_H")
#ifndef UIT_EMP_WEB_DOCUEXTRAS_H_HEADERGUARD
#undef EMP_WEB_DOCUEXTRAS_H
#endif // #ifndef UIT_EMP_WEB_DOCUEXTRAS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_EMSCRIPTENCANVAS_H")
#ifndef UIT_EMP_WEB_EMSCRIPTENCANVAS_H_HEADERGUARD
#undef EMP_WEB_EMSCRIPTENCANVAS_H
#endif // #ifndef UIT_EMP_WEB_EMSCRIPTENCANVAS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_DOCUMENT_H")
#ifndef UIT_EMP_WEB_DOCUMENT_H_HEADERGUARD
#undef EMP_WEB_DOCUMENT_H
#endif // #ifndef UIT_EMP_WEB_DOCUMENT_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_COL_H")
#ifndef UIT_EMP_WEB_TABLE_COL_H_HEADERGUARD
#undef EMP_WEB_TABLE_COL_H
#endif // #ifndef UIT_EMP_WEB_TABLE_COL_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TEXT_H")
#ifndef UIT_EMP_WEB_TEXT_H_HEADERGUARD
#undef EMP_WEB_TEXT_H
#endif // #ifndef UIT_EMP_WEB_TEXT_H_HEADERGUARD

#pragma push_macro("EMP_WEB_DIV_H")
#ifndef UIT_EMP_WEB_DIV_H_HEADERGUARD
#undef EMP_WEB_DIV_H
#endif // #ifndef UIT_EMP_WEB_DIV_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TEXT_AREA_H")
#ifndef UIT_EMP_WEB_TEXT_AREA_H_HEADERGUARD
#undef EMP_WEB_TEXT_AREA_H
#endif // #ifndef UIT_EMP_WEB_TEXT_AREA_H_HEADERGUARD

#pragma push_macro("EMP_WEB_BUTTON_H")
#ifndef UIT_EMP_WEB_BUTTON_H_HEADERGUARD
#undef EMP_WEB_BUTTON_H
#endif // #ifndef UIT_EMP_WEB_BUTTON_H_HEADERGUARD

#pragma push_macro("EMP_EM_FUNCTIONS_H")
#ifndef UIT_EMP_EM_FUNCTIONS_H_HEADERGUARD
#undef EMP_EM_FUNCTIONS_H
#endif // #ifndef UIT_EMP_EM_FUNCTIONS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_FILE_INPUT_H")
#ifndef UIT_EMP_WEB_FILE_INPUT_H_HEADERGUARD
#undef EMP_WEB_FILE_INPUT_H
#endif // #ifndef UIT_EMP_WEB_FILE_INPUT_H_HEADERGUARD

#pragma push_macro("EMP_WEB_TABLE_ROW_GROUP_H")
#ifndef UIT_EMP_WEB_TABLE_ROW_GROUP_H_HEADERGUARD
#undef EMP_WEB_TABLE_ROW_GROUP_H
#endif // #ifndef UIT_EMP_WEB_TABLE_ROW_GROUP_H_HEADERGUARD

#pragma push_macro("WEB_TESTING_MOCHA_TEST_RUNNER_H")
#ifndef UIT_WEB_TESTING_MOCHA_TEST_RUNNER_H_HEADERGUARD
#undef WEB_TESTING_MOCHA_TEST_RUNNER_H
#endif // #ifndef UIT_WEB_TESTING_MOCHA_TEST_RUNNER_H_HEADERGUARD

#pragma push_macro("EMP_WEB_ATTRIBUTES_H")
#ifndef UIT_EMP_WEB_ATTRIBUTES_H_HEADERGUARD
#undef EMP_WEB_ATTRIBUTES_H
#endif // #ifndef UIT_EMP_WEB_ATTRIBUTES_H_HEADERGUARD

#pragma push_macro("EMP_WEB_LISTENERS_H")
#ifndef UIT_EMP_WEB_LISTENERS_H_HEADERGUARD
#undef EMP_WEB_LISTENERS_H
#endif // #ifndef UIT_EMP_WEB_LISTENERS_H_HEADERGUARD

#pragma push_macro("EMP_WEB_STYLE_H")
#ifndef UIT_EMP_WEB_STYLE_H_HEADERGUARD
#undef EMP_WEB_STYLE_H
#endif // #ifndef UIT_EMP_WEB_STYLE_H_HEADERGUARD

#pragma push_macro("EMP_D3_LAYOUT_H")
#ifndef UIT_EMP_D3_LAYOUT_H_HEADERGUARD
#undef EMP_D3_LAYOUT_H
#endif // #ifndef UIT_EMP_D3_LAYOUT_H_HEADERGUARD

#pragma push_macro("EMP_D3_LOAD_DATA_H")
#ifndef UIT_EMP_D3_LOAD_DATA_H_HEADERGUARD
#undef EMP_D3_LOAD_DATA_H
#endif // #ifndef UIT_EMP_D3_LOAD_DATA_H_HEADERGUARD

#pragma push_macro("EMP_D3_AXIS_H")
#ifndef UIT_EMP_D3_AXIS_H_HEADERGUARD
#undef EMP_D3_AXIS_H
#endif // #ifndef UIT_EMP_D3_AXIS_H_HEADERGUARD

#pragma push_macro("EMP_D3_SVG_SHAPES_H")
#ifndef UIT_EMP_D3_SVG_SHAPES_H_HEADERGUARD
#undef EMP_D3_SVG_SHAPES_H
#endif // #ifndef UIT_EMP_D3_SVG_SHAPES_H_HEADERGUARD

#pragma push_macro("EMP_D3_SCALES_H")
#ifndef UIT_EMP_D3_SCALES_H_HEADERGUARD
#undef EMP_D3_SCALES_H
#endif // #ifndef UIT_EMP_D3_SCALES_H_HEADERGUARD

#pragma push_macro("D3_INIT_H")
#ifndef UIT_D3_INIT_H_HEADERGUARD
#undef D3_INIT_H
#endif // #ifndef UIT_D3_INIT_H_HEADERGUARD

#pragma push_macro("EMP_D3_HISTOGRAM_H")
#ifndef UIT_EMP_D3_HISTOGRAM_H_HEADERGUARD
#undef EMP_D3_HISTOGRAM_H
#endif // #ifndef UIT_EMP_D3_HISTOGRAM_H_HEADERGUARD

#pragma push_macro("VISUALIZATION_ELEMENTS_H")
#ifndef UIT_VISUALIZATION_ELEMENTS_H_HEADERGUARD
#undef VISUALIZATION_ELEMENTS_H
#endif // #ifndef UIT_VISUALIZATION_ELEMENTS_H_HEADERGUARD

#pragma push_macro("EMP_VISUALIZATION_UTILS_H")
#ifndef UIT_EMP_VISUALIZATION_UTILS_H_HEADERGUARD
#undef EMP_VISUALIZATION_UTILS_H
#endif // #ifndef UIT_EMP_VISUALIZATION_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_GAME_PAYOFF_MATRIX_H")
#ifndef UIT_EMP_GAME_PAYOFF_MATRIX_H_HEADERGUARD
#undef EMP_GAME_PAYOFF_MATRIX_H
#endif // #ifndef UIT_EMP_GAME_PAYOFF_MATRIX_H_HEADERGUARD

#pragma push_macro("EMP_GAME_MANCALA_H")
#ifndef UIT_EMP_GAME_MANCALA_H_HEADERGUARD
#undef EMP_GAME_MANCALA_H
#endif // #ifndef UIT_EMP_GAME_MANCALA_H_HEADERGUARD

#pragma push_macro("EMP_GAME_OTHELLO_H")
#ifndef UIT_EMP_GAME_OTHELLO_H_HEADERGUARD
#undef EMP_GAME_OTHELLO_H
#endif // #ifndef UIT_EMP_GAME_OTHELLO_H_HEADERGUARD

#pragma push_macro("EMP_GAME_OTHELLO8_H")
#ifndef UIT_EMP_GAME_OTHELLO8_H_HEADERGUARD
#undef EMP_GAME_OTHELLO8_H
#endif // #ifndef UIT_EMP_GAME_OTHELLO8_H_HEADERGUARD

#pragma push_macro("EMP_GENERIC_FUNCTION_H")
#ifndef UIT_EMP_GENERIC_FUNCTION_H_HEADERGUARD
#undef EMP_GENERIC_FUNCTION_H
#endif // #ifndef UIT_EMP_GENERIC_FUNCTION_H_HEADERGUARD

#pragma push_macro("EMP_MEMO_FUNCTIONS_H")
#ifndef UIT_EMP_MEMO_FUNCTIONS_H_HEADERGUARD
#undef EMP_MEMO_FUNCTIONS_H
#endif // #ifndef UIT_EMP_MEMO_FUNCTIONS_H_HEADERGUARD

#pragma push_macro("EMP_FUNCTION_SET_H")
#ifndef UIT_EMP_FUNCTION_SET_H_HEADERGUARD
#undef EMP_FUNCTION_SET_H
#endif // #ifndef UIT_EMP_FUNCTION_SET_H_HEADERGUARD

#pragma push_macro("EMP_FLEX_FUNCTION_H")
#ifndef UIT_EMP_FLEX_FUNCTION_H_HEADERGUARD
#undef EMP_FLEX_FUNCTION_H
#endif // #ifndef UIT_EMP_FLEX_FUNCTION_H_HEADERGUARD

#pragma push_macro("EMP_ANY_FUNCTION_H")
#ifndef UIT_EMP_ANY_FUNCTION_H_HEADERGUARD
#undef EMP_ANY_FUNCTION_H
#endif // #ifndef UIT_EMP_ANY_FUNCTION_H_HEADERGUARD

#pragma push_macro("EMP_CONTIGUOUS_STREAM_H")
#ifndef UIT_EMP_CONTIGUOUS_STREAM_H_HEADERGUARD
#undef EMP_CONTIGUOUS_STREAM_H
#endif // #ifndef UIT_EMP_CONTIGUOUS_STREAM_H_HEADERGUARD

#pragma push_macro("EMP_ASCII_UTILS_H")
#ifndef UIT_EMP_ASCII_UTILS_H_HEADERGUARD
#undef EMP_ASCII_UTILS_H
#endif // #ifndef UIT_EMP_ASCII_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_SERIALIZE_H")
#ifndef UIT_EMP_SERIALIZE_H_HEADERGUARD
#undef EMP_SERIALIZE_H
#endif // #ifndef UIT_EMP_SERIALIZE_H_HEADERGUARD

#pragma push_macro("EMP_SERIALIZE_MACROS_H")
#ifndef UIT_EMP_SERIALIZE_MACROS_H_HEADERGUARD
#undef EMP_SERIALIZE_MACROS_H
#endif // #ifndef UIT_EMP_SERIALIZE_MACROS_H_HEADERGUARD

#pragma push_macro("EMP_FILE_H")
#ifndef UIT_EMP_FILE_H_HEADERGUARD
#undef EMP_FILE_H
#endif // #ifndef UIT_EMP_FILE_H_HEADERGUARD

#pragma push_macro("EMP_NULLSTREAM_H")
#ifndef UIT_EMP_NULLSTREAM_H_HEADERGUARD
#undef EMP_NULLSTREAM_H
#endif // #ifndef UIT_EMP_NULLSTREAM_H_HEADERGUARD

#pragma push_macro("EMP_STREAM_MANAGER_H")
#ifndef UIT_EMP_STREAM_MANAGER_H_HEADERGUARD
#undef EMP_STREAM_MANAGER_H
#endif // #ifndef UIT_EMP_STREAM_MANAGER_H_HEADERGUARD

#pragma push_macro("EMP_TYPE_TRACKER_H")
#ifndef UIT_EMP_TYPE_TRACKER_H_HEADERGUARD
#undef EMP_TYPE_TRACKER_H
#endif // #ifndef UIT_EMP_TYPE_TRACKER_H_HEADERGUARD

#pragma push_macro("EMP_HASH_NAMIFY_H")
#ifndef UIT_EMP_HASH_NAMIFY_H_HEADERGUARD
#undef EMP_HASH_NAMIFY_H
#endif // #ifndef UIT_EMP_HASH_NAMIFY_H_HEADERGUARD

#pragma push_macro("EMP_TIMING_H")
#ifndef UIT_EMP_TIMING_H_HEADERGUARD
#undef EMP_TIMING_H
#endif // #ifndef UIT_EMP_TIMING_H_HEADERGUARD

#pragma push_macro("EMP_KEY_NAME_UTILS_H")
#ifndef UIT_EMP_KEY_NAME_UTILS_H_HEADERGUARD
#undef EMP_KEY_NAME_UTILS_H
#endif // #ifndef UIT_EMP_KEY_NAME_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_VALUE_UTILS_H")
#ifndef UIT_EMP_VALUE_UTILS_H_HEADERGUARD
#undef EMP_VALUE_UTILS_H
#endif // #ifndef UIT_EMP_VALUE_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_STRING_UTILS_H")
#ifndef UIT_EMP_STRING_UTILS_H_HEADERGUARD
#undef EMP_STRING_UTILS_H
#endif // #ifndef UIT_EMP_STRING_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_SOLVE_STATE_H")
#ifndef UIT_EMP_SOLVE_STATE_H_HEADERGUARD
#undef EMP_SOLVE_STATE_H
#endif // #ifndef UIT_EMP_SOLVE_STATE_H_HEADERGUARD

#pragma push_macro("POLYFILL_SPAN_H")
#ifndef UIT_POLYFILL_SPAN_H_HEADERGUARD
#undef POLYFILL_SPAN_H
#endif // #ifndef UIT_POLYFILL_SPAN_H_HEADERGUARD

#pragma push_macro("EMP_VAL_PACK_H")
#ifndef UIT_EMP_VAL_PACK_H_HEADERGUARD
#undef EMP_VAL_PACK_H
#endif // #ifndef UIT_EMP_VAL_PACK_H_HEADERGUARD

#pragma push_macro("EMP_TYPE_TRAITS_H")
#ifndef UIT_EMP_TYPE_TRAITS_H_HEADERGUARD
#undef EMP_TYPE_TRAITS_H
#endif // #ifndef UIT_EMP_TYPE_TRAITS_H_HEADERGUARD

#pragma push_macro("EMP_REFLECTION_H")
#ifndef UIT_EMP_REFLECTION_H_HEADERGUARD
#undef EMP_REFLECTION_H
#endif // #ifndef UIT_EMP_REFLECTION_H_HEADERGUARD

#pragma push_macro("EMP_TYPE_ID_H")
#ifndef UIT_EMP_TYPE_ID_H_HEADERGUARD
#undef EMP_TYPE_ID_H
#endif // #ifndef UIT_EMP_TYPE_ID_H_HEADERGUARD

#pragma push_macro("EMP_META_H")
#ifndef UIT_EMP_META_H_HEADERGUARD
#undef EMP_META_H
#endif // #ifndef UIT_EMP_META_H_HEADERGUARD

#pragma push_macro("EMP_STRING_TYPE_H")
#ifndef UIT_EMP_STRING_TYPE_H_HEADERGUARD
#undef EMP_STRING_TYPE_H
#endif // #ifndef UIT_EMP_STRING_TYPE_H_HEADERGUARD

#pragma push_macro("EMP_CONCEPT_WRAPPER_H")
#ifndef UIT_EMP_CONCEPT_WRAPPER_H_HEADERGUARD
#undef EMP_CONCEPT_WRAPPER_H
#endif // #ifndef UIT_EMP_CONCEPT_WRAPPER_H_HEADERGUARD

#pragma push_macro("EMP_TYPE_PACK_H")
#ifndef UIT_EMP_TYPE_PACK_H_HEADERGUARD
#undef EMP_TYPE_PACK_H
#endif // #ifndef UIT_EMP_TYPE_PACK_H_HEADERGUARD

#pragma push_macro("EMP_ALERT_H")
#ifndef UIT_EMP_ALERT_H_HEADERGUARD
#undef EMP_ALERT_H
#endif // #ifndef UIT_EMP_ALERT_H_HEADERGUARD

#pragma push_macro("EMP_DEBUG_H")
#ifndef UIT_EMP_DEBUG_H_HEADERGUARD
#undef EMP_DEBUG_H
#endif // #ifndef UIT_EMP_DEBUG_H_HEADERGUARD

#pragma push_macro("EMP_CITATION_H")
#ifndef UIT_EMP_CITATION_H_HEADERGUARD
#undef EMP_CITATION_H
#endif // #ifndef UIT_EMP_CITATION_H_HEADERGUARD

#pragma push_macro("EMP_BIBLIOGRAPHY_H")
#ifndef UIT_EMP_BIBLIOGRAPHY_H_HEADERGUARD
#undef EMP_BIBLIOGRAPHY_H
#endif // #ifndef UIT_EMP_BIBLIOGRAPHY_H_HEADERGUARD

#pragma push_macro("EMP_AUTHOR_H")
#ifndef UIT_EMP_AUTHOR_H_HEADERGUARD
#undef EMP_AUTHOR_H
#endif // #ifndef UIT_EMP_AUTHOR_H_HEADERGUARD

#pragma push_macro("EMP_MATCH_BIN_UTILS_H")
#ifndef UIT_EMP_MATCH_BIN_UTILS_H_HEADERGUARD
#undef EMP_MATCH_BIN_UTILS_H
#endif // #ifndef UIT_EMP_MATCH_BIN_UTILS_H_HEADERGUARD

#pragma push_macro("EMP_MATCH_BIN_METRICS_H")
#ifndef UIT_EMP_MATCH_BIN_METRICS_H_HEADERGUARD
#undef EMP_MATCH_BIN_METRICS_H
#endif // #ifndef UIT_EMP_MATCH_BIN_METRICS_H_HEADERGUARD

#pragma push_macro("EMP_MATCH_BIN_SELECTORS_H")
#ifndef UIT_EMP_MATCH_BIN_SELECTORS_H_HEADERGUARD
#undef EMP_MATCH_BIN_SELECTORS_H
#endif // #ifndef UIT_EMP_MATCH_BIN_SELECTORS_H_HEADERGUARD

#pragma push_macro("EMP_MATCH_BIN_REGULATORS_H")
#ifndef UIT_EMP_MATCH_BIN_REGULATORS_H_HEADERGUARD
#undef EMP_MATCH_BIN_REGULATORS_H
#endif // #ifndef UIT_EMP_MATCH_BIN_REGULATORS_H_HEADERGUARD

#endif // #ifdef UIT_VENDORIZE_EMP
