#ifdef UIT_VENDORIZE_EMP

#pragma push_macro("EMP_ALWAYS_ASSERT_HPP")
#undef EMP_ALWAYS_ASSERT_HPP
#ifdef UIT_EMP_ALWAYS_ASSERT_HPP_HEADERGUARD
#define EMP_ALWAYS_ASSERT_HPP
#endif

#pragma push_macro("EMP_ARRAY_H")
#undef EMP_ARRAY_H
#ifdef UIT_EMP_ARRAY_H_HEADERGUARD
#define EMP_ARRAY_H
#endif

#pragma push_macro("EMP_ASSERT_HPP")
#undef EMP_ASSERT_HPP
#ifdef UIT_EMP_ASSERT_HPP_HEADERGUARD
#define EMP_ASSERT_HPP
#endif

#pragma push_macro("EMP_ASSERT_TRIGGER_HPP")
#undef EMP_ASSERT_TRIGGER_HPP
#ifdef UIT_EMP_ASSERT_TRIGGER_HPP_HEADERGUARD
#define EMP_ASSERT_TRIGGER_HPP
#endif

#pragma push_macro("EMP_ASSOCIATIVE_ARRAY_CACHE_HPP")
#undef EMP_ASSOCIATIVE_ARRAY_CACHE_HPP
#ifdef UIT_EMP_ASSOCIATIVE_ARRAY_CACHE_HPP_HEADERGUARD
#define EMP_ASSOCIATIVE_ARRAY_CACHE_HPP
#endif

#pragma push_macro("EMP_BASE_EMP_NAMESPACE_HPP")
#undef EMP_BASE_EMP_NAMESPACE_HPP
#ifdef UIT_EMP_BASE_EMP_NAMESPACE_HPP_HEADERGUARD
#define EMP_BASE_EMP_NAMESPACE_HPP
#endif

#pragma push_macro("EMP_BITSET_UTILS_H")
#undef EMP_BITSET_UTILS_H
#ifdef UIT_EMP_BITSET_UTILS_H_HEADERGUARD
#define EMP_BITSET_UTILS_H
#endif

#pragma push_macro("EMP_BIT_SET_HPP")
#undef EMP_BIT_SET_HPP
#ifdef UIT_EMP_BIT_SET_HPP_HEADERGUARD
#define EMP_BIT_SET_HPP
#endif

#pragma push_macro("EMP_BIT_VECTOR_H")
#undef EMP_BIT_VECTOR_H
#ifdef UIT_EMP_BIT_VECTOR_H_HEADERGUARD
#define EMP_BIT_VECTOR_H
#endif

#pragma push_macro("EMP_CACHE_H")
#undef EMP_CACHE_H
#ifdef UIT_EMP_CACHE_H_HEADERGUARD
#define EMP_CACHE_H
#endif

#pragma push_macro("EMP_CONFIG_H")
#undef EMP_CONFIG_H
#ifdef UIT_EMP_CONFIG_H_HEADERGUARD
#define EMP_CONFIG_H
#endif

#pragma push_macro("EMP_CONFIG_MANAGER_H")
#undef EMP_CONFIG_MANAGER_H
#ifdef UIT_EMP_CONFIG_MANAGER_H_HEADERGUARD
#define EMP_CONFIG_MANAGER_H
#endif

#pragma push_macro("EMP_CONST_H")
#undef EMP_CONST_H
#ifdef UIT_EMP_CONST_H_HEADERGUARD
#define EMP_CONST_H
#endif

#pragma push_macro("EMP_CONTIGUOUS_STREAM_H")
#undef EMP_CONTIGUOUS_STREAM_H
#ifdef UIT_EMP_CONTIGUOUS_STREAM_H_HEADERGUARD
#define EMP_CONTIGUOUS_STREAM_H
#endif

#pragma push_macro("EMP_DATA_FILE_H")
#undef EMP_DATA_FILE_H
#ifdef UIT_EMP_DATA_FILE_H_HEADERGUARD
#define EMP_DATA_FILE_H
#endif

#pragma push_macro("EMP_DATA_NODE_H")
#undef EMP_DATA_NODE_H
#ifdef UIT_EMP_DATA_NODE_H_HEADERGUARD
#define EMP_DATA_NODE_H
#endif

#pragma push_macro("EMP_DEPOSITORY_ENTRY_HPP")
#undef EMP_DEPOSITORY_ENTRY_HPP
#ifdef UIT_EMP_DEPOSITORY_ENTRY_HPP_HEADERGUARD
#define EMP_DEPOSITORY_ENTRY_HPP
#endif

#pragma push_macro("EMP_DISTRIBUTION_H")
#undef EMP_DISTRIBUTION_H
#ifdef UIT_EMP_DISTRIBUTION_H_HEADERGUARD
#define EMP_DISTRIBUTION_H
#endif

#pragma push_macro("EMP_ERRORS_H")
#undef EMP_ERRORS_H
#ifdef UIT_EMP_ERRORS_H_HEADERGUARD
#define EMP_ERRORS_H
#endif

#pragma push_macro("EMP_FUNCTION_SET_H")
#undef EMP_FUNCTION_SET_H
#ifdef UIT_EMP_FUNCTION_SET_H_HEADERGUARD
#define EMP_FUNCTION_SET_H
#endif

#pragma push_macro("EMP_HASH_NAMIFY_H")
#undef EMP_HASH_NAMIFY_H
#ifdef UIT_EMP_HASH_NAMIFY_H_HEADERGUARD
#define EMP_HASH_NAMIFY_H
#endif

#pragma push_macro("EMP_HASH_UTILS_H")
#undef EMP_HASH_UTILS_H
#ifdef UIT_EMP_HASH_UTILS_H_HEADERGUARD
#define EMP_HASH_UTILS_H
#endif

#pragma push_macro("EMP_INDEX_MAP_H")
#undef EMP_INDEX_MAP_H
#ifdef UIT_EMP_INDEX_MAP_H_HEADERGUARD
#define EMP_INDEX_MAP_H
#endif

#pragma push_macro("EMP_IS_STREAMABLE_HPP")
#undef EMP_IS_STREAMABLE_HPP
#ifdef UIT_EMP_IS_STREAMABLE_HPP_HEADERGUARD
#define EMP_IS_STREAMABLE_HPP
#endif

#pragma push_macro("EMP_KEY_NAME_UTILS_H")
#undef EMP_KEY_NAME_UTILS_H
#ifdef UIT_EMP_KEY_NAME_UTILS_H_HEADERGUARD
#define EMP_KEY_NAME_UTILS_H
#endif

#pragma push_macro("EMP_MACROS_H")
#undef EMP_MACROS_H
#ifdef UIT_EMP_MACROS_H_HEADERGUARD
#define EMP_MACROS_H
#endif

#pragma push_macro("EMP_MACRO_MATH_H")
#undef EMP_MACRO_MATH_H
#ifdef UIT_EMP_MACRO_MATH_H_HEADERGUARD
#define EMP_MACRO_MATH_H
#endif

#pragma push_macro("EMP_MAP_H")
#undef EMP_MAP_H
#ifdef UIT_EMP_MAP_H_HEADERGUARD
#define EMP_MAP_H
#endif

#pragma push_macro("EMP_MAP_PROXY_H")
#undef EMP_MAP_PROXY_H
#ifdef UIT_EMP_MAP_PROXY_H_HEADERGUARD
#define EMP_MAP_PROXY_H
#endif

#pragma push_macro("EMP_MAP_UTILS_H")
#undef EMP_MAP_UTILS_H
#ifdef UIT_EMP_MAP_UTILS_H_HEADERGUARD
#define EMP_MAP_UTILS_H
#endif

#pragma push_macro("EMP_MATCH_BIN_METRICS_H")
#undef EMP_MATCH_BIN_METRICS_H
#ifdef UIT_EMP_MATCH_BIN_METRICS_H_HEADERGUARD
#define EMP_MATCH_BIN_METRICS_H
#endif

#pragma push_macro("EMP_MATCH_DEPOSITORY_HPP")
#undef EMP_MATCH_DEPOSITORY_HPP
#ifdef UIT_EMP_MATCH_DEPOSITORY_HPP_HEADERGUARD
#define EMP_MATCH_DEPOSITORY_HPP
#endif

#pragma push_macro("EMP_MATH_H")
#undef EMP_MATH_H
#ifdef UIT_EMP_MATH_H_HEADERGUARD
#define EMP_MATH_H
#endif

#pragma push_macro("EMP_META_H")
#undef EMP_META_H
#ifdef UIT_EMP_META_H_HEADERGUARD
#define EMP_META_H
#endif

#pragma push_macro("EMP_NATIVE_ASSERT_TRIGGER_HPP")
#undef EMP_NATIVE_ASSERT_TRIGGER_HPP
#ifdef UIT_EMP_NATIVE_ASSERT_TRIGGER_HPP_HEADERGUARD
#define EMP_NATIVE_ASSERT_TRIGGER_HPP
#endif

#pragma push_macro("EMP_NULLSTREAM_H")
#undef EMP_NULLSTREAM_H
#ifdef UIT_EMP_NULLSTREAM_H_HEADERGUARD
#define EMP_NULLSTREAM_H
#endif

#pragma push_macro("EMP_OPTIONAL_H")
#undef EMP_OPTIONAL_H
#ifdef UIT_EMP_OPTIONAL_H_HEADERGUARD
#define EMP_OPTIONAL_H
#endif

#pragma push_macro("EMP_PLUS_COUNTDOWN_REGULATOR_HPP")
#undef EMP_PLUS_COUNTDOWN_REGULATOR_HPP
#ifdef UIT_EMP_PLUS_COUNTDOWN_REGULATOR_HPP_HEADERGUARD
#define EMP_PLUS_COUNTDOWN_REGULATOR_HPP
#endif

#pragma push_macro("EMP_PTR_H")
#undef EMP_PTR_H
#ifdef UIT_EMP_PTR_H_HEADERGUARD
#define EMP_PTR_H
#endif

#pragma push_macro("EMP_QUEUECACHE_H")
#undef EMP_QUEUECACHE_H
#ifdef UIT_EMP_QUEUECACHE_H_HEADERGUARD
#define EMP_QUEUECACHE_H
#endif

#pragma push_macro("EMP_RANDOM_H")
#undef EMP_RANDOM_H
#ifdef UIT_EMP_RANDOM_H_HEADERGUARD
#define EMP_RANDOM_H
#endif

#pragma push_macro("EMP_RANDOM_UTILS_H")
#undef EMP_RANDOM_UTILS_H
#ifdef UIT_EMP_RANDOM_UTILS_H_HEADERGUARD
#define EMP_RANDOM_UTILS_H
#endif

#pragma push_macro("EMP_RANGE_H")
#undef EMP_RANGE_H
#ifdef UIT_EMP_RANGE_H_HEADERGUARD
#define EMP_RANGE_H
#endif

#pragma push_macro("EMP_RANKED_SELECTOR_HPP")
#undef EMP_RANKED_SELECTOR_HPP
#ifdef UIT_EMP_RANKED_SELECTOR_HPP_HEADERGUARD
#define EMP_RANKED_SELECTOR_HPP
#endif

#pragma push_macro("EMP_REFLECTION_H")
#undef EMP_REFLECTION_H
#ifdef UIT_EMP_REFLECTION_H_HEADERGUARD
#define EMP_REFLECTION_H
#endif

#pragma push_macro("EMP_SMALL_VECTOR_HPP")
#undef EMP_SMALL_VECTOR_HPP
#ifdef UIT_EMP_SMALL_VECTOR_HPP_HEADERGUARD
#define EMP_SMALL_VECTOR_HPP
#endif

#pragma push_macro("EMP_STRING_TYPE_H")
#undef EMP_STRING_TYPE_H
#ifdef UIT_EMP_STRING_TYPE_H_HEADERGUARD
#define EMP_STRING_TYPE_H
#endif

#pragma push_macro("EMP_STRING_UTILS_H")
#undef EMP_STRING_UTILS_H
#ifdef UIT_EMP_STRING_UTILS_H_HEADERGUARD
#define EMP_STRING_UTILS_H
#endif

#pragma push_macro("EMP_TUPLE_UTILS_H")
#undef EMP_TUPLE_UTILS_H
#ifdef UIT_EMP_TUPLE_UTILS_H_HEADERGUARD
#define EMP_TUPLE_UTILS_H
#endif

#pragma push_macro("EMP_TYPE_ID_H")
#undef EMP_TYPE_ID_H
#ifdef UIT_EMP_TYPE_ID_H_HEADERGUARD
#define EMP_TYPE_ID_H
#endif

#pragma push_macro("EMP_TYPE_PACK_H")
#undef EMP_TYPE_PACK_H
#ifdef UIT_EMP_TYPE_PACK_H_HEADERGUARD
#define EMP_TYPE_PACK_H
#endif

#pragma push_macro("EMP_TYPE_TRAITS_H")
#undef EMP_TYPE_TRAITS_H
#ifdef UIT_EMP_TYPE_TRAITS_H_HEADERGUARD
#define EMP_TYPE_TRAITS_H
#endif

#pragma push_macro("EMP_UNORDERED_INDEX_MAP_H")
#undef EMP_UNORDERED_INDEX_MAP_H
#ifdef UIT_EMP_UNORDERED_INDEX_MAP_H_HEADERGUARD
#define EMP_UNORDERED_INDEX_MAP_H
#endif

#pragma push_macro("EMP_UNORDERED_MAP_H")
#undef EMP_UNORDERED_MAP_H
#ifdef UIT_EMP_UNORDERED_MAP_H_HEADERGUARD
#define EMP_UNORDERED_MAP_H
#endif

#pragma push_macro("EMP_VAL_PACK_H")
#undef EMP_VAL_PACK_H
#ifdef UIT_EMP_VAL_PACK_H_HEADERGUARD
#define EMP_VAL_PACK_H
#endif

#pragma push_macro("EMP_VECTOR_H")
#undef EMP_VECTOR_H
#ifdef UIT_EMP_VECTOR_H_HEADERGUARD
#define EMP_VECTOR_H
#endif

#endif // #ifdef UIT_VENDORIZE_EMP
