#ifdef UIT_VENDORIZE_EMP

#pragma push_macro("EMP_ALWAYS_ASSERT_HPP")
#undef EMP_ALWAYS_ASSERT_HPP
#ifdef UIT_EMP_ALWAYS_ASSERT_HPP_HEADERGUARD
#define EMP_ALWAYS_ASSERT_HPP
#endif

#pragma push_macro("EMP_ASSERT_HPP")
#undef EMP_ASSERT_HPP
#ifdef UIT_EMP_ASSERT_HPP_HEADERGUARD
#define EMP_ASSERT_HPP
#endif

#pragma push_macro("EMP_ASSERT_TRIGGER_HPP")
#undef EMP_ASSERT_TRIGGER_HPP
#ifdef UIT_EMP_ASSERT_TRIGGER_HPP_HEADERGUARD
#define EMP_ASSERT_TRIGGER_HPP
#endif

#pragma push_macro("EMP_BASE_EMP_NAMESPACE_HPP")
#undef EMP_BASE_EMP_NAMESPACE_HPP
#ifdef UIT_EMP_BASE_EMP_NAMESPACE_HPP_HEADERGUARD
#define EMP_BASE_EMP_NAMESPACE_HPP
#endif

#pragma push_macro("EMP_IS_STREAMABLE_HPP")
#undef EMP_IS_STREAMABLE_HPP
#ifdef UIT_EMP_IS_STREAMABLE_HPP_HEADERGUARD
#define EMP_IS_STREAMABLE_HPP
#endif

#pragma push_macro("EMP_MACROS_H")
#undef EMP_MACROS_H
#ifdef UIT_EMP_MACROS_H_HEADERGUARD
#define EMP_MACROS_H
#endif

#pragma push_macro("EMP_MACRO_MATH_H")
#undef EMP_MACRO_MATH_H
#ifdef UIT_EMP_MACRO_MATH_H_HEADERGUARD
#define EMP_MACRO_MATH_H
#endif

#pragma push_macro("EMP_NATIVE_ASSERT_TRIGGER_HPP")
#undef EMP_NATIVE_ASSERT_TRIGGER_HPP
#ifdef UIT_EMP_NATIVE_ASSERT_TRIGGER_HPP_HEADERGUARD
#define EMP_NATIVE_ASSERT_TRIGGER_HPP
#endif

#endif // #ifdef UIT_VENDORIZE_EMP
