TARGET_NAMES += DyadicTopologyFactory
TARGET_NAMES += RingTopologyFactory
TARGET_NAMES += TopoNode
TARGET_NAMES += LoopTopologyFactory
TARGET_NAMES += TopoEdge
TARGET_NAMES += TopoNodeInput
TARGET_NAMES += ProConTopologyFactory
TARGET_NAMES += Topology
TARGET_NAMES += TopoNodeOutput

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
