TARGET_NAMES += AggregatedOutletDuct
TARGET_NAMES += BufferedOutletDuct
TARGET_NAMES += PooledOutletDuct

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateMultiproc
