TARGET_NAMES += inflate
TARGET_NAMES += NamedArrayElement
TARGET_NAMES += untar

TO_ROOT := $(shell git rev-parse --show-cdup)

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
