TARGET_NAMES += get_exec_instance_uuid
TARGET_NAMES += get_proc_instance_uuid
TARGET_NAMES += get_thread_instance_uuid
TARGET_NAMES += NamedArrayElement
TARGET_NAMES += SetSeparator

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/tests/MaketemplateUniproc
